site_name: Krait
repo_url: https://github.com/mtrdesign/krait
theme:
  name: material
  custom_dir: theme
  logo: assets/krait-full-logo.svg
  favicon: assets/krait-icon-logo.png
  features:
    - header.autohide
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: lime

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mtrdesign
  annotate:
    json: [ .s2 ] # (1)!

nav:
  - Overview: index.md
  - Installation & Usage Guide:
      - Installation: installation-guide.md
      - Usage: usage.md
#  - Core Components: core-components.md
  - Core Components:
      - Table Definition Classes: core-components/table-definition-classes.md
      - Table Columns: core-components/table-columns.md
      - Table Controller: core-components/table-controller.md
      - Dynamic Table Component: core-components/dynamic-table-component.md
  - Contribution: contribution.md
