name: Draft Release
run-name: Draft Release of ${{ github.ref_name }} triggered by @${{ github.actor }}

on:
  push:
    branches:
      - "[0-9]+.x"

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  draft-release:
    name: Draft Github Release
    if: github.actor != 'mtrpackageversionsmanager[bot]'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create/Update the draft release
        uses: ./.github/actions/draft-release
        with:
          branch_name: ${{ github.ref_name }}
