name: CI Validation

on:
  pull_request:
    branches:
      - "[0-9]+.x"

defaults:
  run:
    working-directory: ./krait-ui

env:
  NODE_VERSION: "20.16.0"
  PHP_VERSION: "8.2.22"

jobs:
  check_pr_label:
    name: Check PR Label
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-22.04
    steps:
      - name: Check PR contains at least one valid label
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "Feature, Improvement, Dependency, Deprecated, Bug, IgnoreForRelease, Documentation, Removed, GHA"
          disable-reviews: true

  lint-checks:
    name: Lint Checks
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "krait-ui/package-lock.json"

      - name: Install npm dependencies
        run: npm ci

      - name: Run Prettier check
        run: npm run prettier

      - name: Run Lint check
        run: npm run lint

      - name: Build
        run: npm run build
