name: Draft Release
run-name: Draft Release triggered by @${{ github.actor }}

on:
  push:
    branches:
      - "[0-9]+.x"
  pull_request:

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  draft-release:
    name: Draft Github Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create/Update Draft Release
        uses: ./.github/actions/draft-release
        with:
          branch_name: "1.x"
