name: PR Opened

on:
  pull_request:
    types: [ opened ]
    branches:
      - fix-github-actions

env:
  NODE_VERSION: '20.16.0'
  PHP_VERSION: '8.2.22'

jobs:
  run-tests:
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Retrieve the npm dependencies cache
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: npm-dependencies-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            npm-dependencies-${{ hashFiles('./package-lock.json') }}
            npm-dependencies-

      - name: Install npm dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Prettier Check
        run: npm run prettier

      - name: Build
        run: npm run build